name: Dependabot auto-merge

on:
  pull_request:

permissions: {}

jobs:
  auto-merge:
    if: github.actor == 'dependabot[bot]'
    permissions:
      contents: write
      pull-requests: write
    uses: damien-robotsix/robotsix-github-workflows/.github/workflows/dependabot-auto-merge.yml@86dae89b637dad27ddba0aaa5f9430e083288365 # main
