name: Docs

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    uses: damien-robotsix/robotsix-github-workflows/.github/workflows/python-docs.yml@7314c9b6c2b536ca81023e8841f272b72733262e # main
